name: Docker Image CI/CD - Release - RW-HPS

on:
#  release:
#    types: [published]
  push:
    tags:
      - '*.*.*'

jobs:
  # build and push
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: |
          #echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          # 去掉前面的 refs/tags/
          echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          echo ::set-output name=IMAGE_NAME::rw-hps

      - name: Login to Registry - ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image and Push - ghcr.io
        # --platform=linux/amd64,linux/arm64/v8 \
        run: |
          declare -l IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.IMAGE_NAME }}
          VERSION=${{ steps.vars.outputs.RELEASE_VERSION }}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file Dockerfile \
          --tag $IMAGE_ID:$VERSION \
          .

      - name: Build Image and Push - latest - ghcr.io
        # --platform=linux/amd64,linux/arm64/v8 \
        run: |
          declare -l IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.IMAGE_NAME }}
          echo IMAGE_ID=$IMAGE_ID
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file Dockerfile \
          --tag $IMAGE_ID:latest \
          .
