name: Docker Image CI/CD - Beta - RW-HPS

on:
  push:
    branches: [ master ]

jobs:
  # build and push
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release, prerelease"
          view_top: 1  

      - name: Set outputs
        id: vars
        run: |
          echo ::set-output name=IMAGE_NAME::rw-hps

      - name: Login to Registry - ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Image and Push - ghcr.io
        # push: last_release-beta
        # --platform=linux/amd64,linux/arm64/v8 \
        run: |
          declare -l IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.IMAGE_NAME }}
          VERSION=${{ steps.last_release.outputs.tag_name }}-beta
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file Dockerfile \
          --tag $IMAGE_ID:$VERSION \
          .
